on: push
name: ğŸš€ Deploy website on push
jobs:
  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Get latest code
      uses: actions/checkout@v2.3.2
    - run: npm install
    - run: npm build
    
    - name: ğŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.tomaldy.com
        username: tomaldyc
        password: ${{ secrets.ftp_password }}
        server-dir: cpanel.tomaldy.com/public/
        local-dir: ./dist/
